version: "3.8"


services:
  fpm:
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"

  bot:
    container_name: bot-container
    environment:
      PYTHONUNBUFFERED: 1
      MISTRAL_API_KEY: /run/secrets/api_mistral
      QDRANT_API_KEY:  /run/secrets/api_qdrant
      DISCORD_API_KEY: /run/secrets/api_discord
    build:
      context: .
    ports:
      - 80:80
    networks:
      - net

secrets:
   api_mistral:
     file: api_mistral.txt
   api_qdrant:
     file: api_qdrant.txt
   api_discord:
     file: api_discord.txt

networks:
  net:
    driver: bridge