version: "3.8"


services:
  bot:
    container_name: bot-container
    environment:
      PYTHONUNBUFFERED: 1
      MISTRAL_API_KEY: /run/secrets/api_mistral
      QDRANT_API_KEY:  /run/secrets/api_qdrant
      DISCORD_API_KEY: /run/secrets/api_discord
    secrets:
      - api_mistral
      - api_qdrant
      - api_discord
    build:
      context: .
    ports:
      - 80:80
    networks:
      - net

secrets:
   api_mistral:
     file: ./app/api_mistral.txt
   api_qdrant:
     file: ./app/api_qdrant.txt
   api_discord:
     file: ./app/api_discord.txt

networks:
  net:
    driver: bridge