version: "3.0"


services:
  fpm:
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"

  bot:
    container_name: bot-container
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
    ports:
      - 80:80
    networks:
      - net

networks:
  net:
    driver: bridge